# Install/Configure pass
- hosts: all
  become: yes
  environment:
    K8S_AUTH_KUBECONFIG: "{{ k8s_auth_kubeconfig | default(lookup('env', 'KUBECONFIG')) | default('/etc/kubernetes/admin.conf', true) }}"
  roles:
    - { role: k8s_install, k8s_install_traefik: false }

# Post-install components (only apply if cluster exists)
- hosts: primary
  become: yes
  environment:
    K8S_AUTH_KUBECONFIG: /etc/kubernetes/admin.conf
  roles:
    - { role: nvidia_gpu_operator }
    - { role: nvidia_net_operator }
    - {
        role: traefik,
        tags: ['traefik']
      }
    - { role: longhorn }
    - { role: kuberay, tags: ['kuberay'] }

- hosts: primary
  become: yes
  roles:
    - { role: vllm_ray, tags: ['vllm'] }
    - { role: openwebui }

- hosts: workers
  become: yes
  roles:
    - { role: join_workers, tags: ['join'] }
