# Install/Configure pass
- hosts: all
  become: yes
  roles:
    - { role: k8s_install, k8s_install_traefik: false }

# Post-install components (only apply if cluster exists)
- hosts: primary
  become: yes
  environment:
    K8S_AUTH_KUBECONFIG: /etc/kubernetes/admin.conf
  roles:
    - { role: nvidia_gpu_operator }
    - { role: nvidia_net_operator }
    - {
        role: traefik,
        tags: ['traefik']
      }
    - { role: longhorn }

- hosts: primary
  become: yes
  roles:
    - { role: trtllm_build, tags: ['trtllm_build','build'] }

- hosts: primary
  become: yes
  roles:
    - { role: triton_trtllm }
    - { role: openai_proxy }
    - { role: openwebui }
