---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family | default('Debian') == 'Debian'

    - name: Ensure base packages present
      ansible.builtin.package:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Placeholder task for repo sanity
      ansible.builtin.debug:
        msg: "Molecule converge OK"
